# 全局日志级别 (DEBUG/INFO/WARN/ERROR/FATAL)
log_level: INFO

# 日志文件目录
log_dir: ./logs

# 控制台输出配置
console:
  enable: true          # 是否启用控制台输出
  level: DEBUG          # 控制台日志级别
  color: true           # 是否启用彩色输出

# 文件输出配置
file:
  enable: true          # 是否启用文件输出
  level: INFO           # 文件日志级别
  filename: app.log     # 日志文件名
  max_size: 100         # 单个文件最大大小(MB)
  max_backups: 7        # 保留的备份文件数量
  max_age: 30           # 文件保留天数
  compress: true        # 是否压缩备份文件
  formatter: json       # 日志格式: plain/json